config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :blog_posts do
    collection do
      get :search
    end
  end
  resources :comments, only: %i[create]

  root "blog_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  include PgSearch
  extend FriendlyId

  validates :title, :author, :body, presence: true
  has_many :comments, dependent: :destroy
  friendly_id :title, use: :slugged

  pg_search_scope :search,
                  against: %i[title author body],
                  associated_against: { comments: %i[body] }

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :body, presence: true
  belongs_to :blog_post, class_name: "BlogPost"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, except: [:index, :new, :create]
  before_action :set_locale


  def index
    @blog_posts = BlogPost.order(created_at: :desc)
  end

  def search
    @blog_posts = BlogPost.search(search_params[:q])
  end

  def show
    @comments = @blog_post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      redirect_to @blog_post, notice: 'O post foi criado com  sucesso.'
    else
      flash.now[:alert] = @blog_post.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.comments.destroy_all
    @blog_post.destroy
    redirect_to root_path
  end

  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :author, :body)
  end

  def search_params
    params.permit(:q)
  end

  def set_blog_post
    @blog_post = BlogPost.friendly.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
  def set_locale
    I18n.locale = current_user.try(:locale) || I18n.default_locale
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create!(comments_params)

    redirect_to comment.blog_post, notice: 'O seu comentário foi enviado.'
  end
  private
  def comments_params
    params.require(:comment).permit(:blog_post_id, :author, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_blog_post.html.erb
<div class="card bg-light mb-4">
  <div class="card-body" >
  <h4><%= link_to blog_post.title, blog_post %></h4>

    <div class="text-muted mb-2">
      <em> Por <%= blog_post.author %> (<%= l blog_post.created_at, format: :long %>)</em>
    </div>
    <p><%= blog_post.body.truncate(200) %></p>

    <p class="text-muted"><%= pluralize blog_post.comments.count, 'Comentário' %></p>
    <%= link_to "Ler Artigo", blog_post,  class: 'btn btn-warning' %>
    <%= link_to "Editar", edit_blog_post_path(blog_post), class:'btn btn-secondary' %>

  </div>
</div>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div class="form-group" >
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group"  >
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 5 %>
  </div>

  <div>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_black: true %>

  </div>
  <%= form.submit 'Criar', class: 'btn btn-warning mt-2', data: { disable_with: 'Criando...' }%>

<% end %>

app/views/blog_posts/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>
      <h1 class="text-center" >Editar blog post</h1>
      <%= render partial: "form", locals: {blog_post: @blog_post} %>
      <%= button_to "Delete", @blog_post, method: :delete, data:{turbo_confirm: "Tem certeza?"}, class: " btn btn-outline-danger btn-sm mt-2 " %>
    </div>
  </div>
</div>

app/views/blog_posts/index.html.erb
<h1 class="m-2">Meu Blog</h1>

<% @blog_posts.each do |blog_post| %>
  <%= render(blog_post) %>
<% end %>

<hr>

<div class="text-right">
  <%= link_to "Criar novo post", new_blog_post_path, class: 'btn btn-warning m-2'  %>
</div>
<hr>

app/views/blog_posts/new.html.erb
<h1>Novo Blog Post</h1>

<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/search.html.erb
<h2 class="text-muted">
  <% if @blog_psts.any? %>
    <%= pluralize (@blog_posts.count 'resulado' ) %>encontrados:
    <% else %>
  Nenhum resultado encontrado
    <% end  %>
</h2>


<% @blog_posts.each do || %>
  <%= render blog_post %>
<% end %>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed_in? %>
<div class="shadow bg-light p-5 rounded">
  <div class="text-center mb-5">
    <h1><%= @blog_post.title %></h1>
    <p class="text-muted">
      <strong>Por <%= @blog_post.author  %></strong><br>
      <%= l @blog_post.created_at, format: :long %>
    </p>
  </div>


  <div class="px-5">
       <%= @blog_post.body.gsub("\n", "<br>").html_safe %>
  </div>
</div>

<div class="m-5">
  <div class="text-center">
    <h4>
      <%= pluralize(@blog_post.comments.count, 'Comentário' ) %>

      <% if @blog_post.comments.empty?  %>
        <span class="badge badge-warning">Seja o primeiro a comentar!</span>
      <% end %>
    </h4>
  </div>

  <div class="shadow-sm m-3 p-3 bg-light rounded">
    <%= form_with model: @comment, local: true do |form| %>
      <%= form.hidden_field :blog_post_id, value: @blog_post.id %>
      <div class="form-group">
        <%= form.label :author, 'Autor(a)' %>
        <%= form.text_field :author, class: 'form-control', required: true %>
      </div>

      <div class="form-group"  >
        <%= form.label :body,  'Comentário' %>
        <%= form.text_area :body, class: 'form-control', rows: 5, required: true %>
      </div>
      <%= form.submit 'Enviar', class: 'btn btn-warning m-2', data: { disable_with: 'Enviando...' }%>
    <% end %>
  </div>

  <% @comments.each do |comment| %>
    <div class="shadow-sm m-3 p-3 bg-light rounded">
      <div class="row">
        <div class="col">
          <strong><%= comment.author %></strong>
        </div>

        <div class="col text-right">

            <em  class="btn btn-warning" data-bs-toggle="tooltip" data-bs-placement="top" title="<%= comment.created_at.strftime('%d/%m/%Y %H:%M:%S') %>">
              <%= time_ago_in_words(comment.created_at) %> atrás
            </em>
        </div>
      </div>

      <hr>

      <%= sanitize(comment.body.gsub("\n", "<br>")).html_safe %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>JulsilTecnoBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <style>
      body {
          padding-top: 56px;
      }
      @media (min-width: 768px) {
          body {
              padding-top: 76px;
          }
      }

      {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      }
      .navbar {
          background-color: #343a40;
      }
      .jumbotron {
          background-color: #343a40;
          color: #fff;
      }

  </style>
</head>
<body class="bg-light">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag "programador.png", alt: "Programador Codificando", width: 40, height: 40, class: 'd-inline-block align-text-top' %>
      JulsilTecnoBlog
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "New blog post", new_blog_post_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container mt-4">
  <div class="jumbotron text-warning text-center p-4 mb-4">
    <%= link_to root_path, class: 'text-white' do %>
      <%= image_tag "programador.png", alt: "Programador Codificando", width: 200, class: 'mb-3' %>
      <h1 class="display-4">JulsilTecnoBlog: Insights de Código</h1>
    <% end %>
    <p class="lead">Explorando Linguagens, Ferramentas e Técnicas de Programação.</p>
  </div>

  <div class="row">
    <div class="col-md-8">
      <%= yield %>
    </div>
  </div>
</div>

<footer class="bg-dark text-white text-center mt-5 p-4">
  <div class="container">
    <p class="mb-0">Copyright:  JulsilTecnoBlog <%= Date.current.year %></p>
  </div>
</footer>

</body>
</html>